import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import axios from 'axios';
import {LayoutDashboard,ShoppingCart,PackageSearch,ClipboardList,Box,MapPin,Truck,AlertTriangle,RefreshCw,ArrowRightLeft,CheckCircle2,Clock3,Search} from 'lucide-react';
import './styles.css';

const API='http://localhost:5000/api';
const api=axios.create({baseURL:API});
const money=n=>`₹${Number(n||0).toLocaleString('en-IN')}`;
const fmt=d=>d?new Date(d).toLocaleString([], {day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}):'-';

function App(){
 const [page,setPage]=useState('Dashboard'); const [refresh,setRefresh]=useState(0);
 const nav=[['Dashboard',LayoutDashboard],['Orders',ShoppingCart],['Inventory',PackageSearch],['Picking',ClipboardList],['Packing',Box],['Staging',MapPin],['Shipping',Truck],['Issues',AlertTriangle]];
 const content={Dashboard:<Dashboard go={setPage}/>,Orders:<Orders go={setPage} refresh={refresh}/>,Inventory:<Inventory refresh={refresh}/>,Picking:<Queue status="Picking" next="Packed" title="Picking Queue" refresh={refresh}/>,Packing:<Queue status="Packed" next="Staged" title="Packing Queue" refresh={refresh}/>,Staging:<Queue status="Staged" next="Shipped" title="Staging & Shipping Queue" refresh={refresh}/>,Shipping:<Shipping refresh={refresh}/>,Issues:<Issues refresh={refresh}/>};
 return <div className="app"><aside><div className="brand"><div className="brand-mark">FH</div><div><b>Fulfillment Hub</b><span>XYZ Operations</span></div></div><nav>{nav.map(([n,I])=><button key={n} className={page===n?'active':''} onClick={()=>setPage(n)}><I size={18}/>{n}</button>)}</nav><div className="sidebar-note"><b>Simple by design</b><span>Built for office & warehouse teams.</span></div></aside><main><header><div><div className="eyebrow">XYZ / OPERATIONS</div><h1>{page}</h1></div><button className="icon-btn" onClick={()=>setRefresh(x=>x+1)} title="Refresh"><RefreshCw size={18}/></button></header>{content[page]}</main></div>
}

function Dashboard({go}){const [d,setD]=useState(null);useEffect(()=>{api.get('/dashboard').then(r=>setD(r.data))},[]);if(!d)return <Loading/>;return <>
 <div className="stats">{[['Total Orders',d.total_orders,ShoppingCart,'neutral'],['Priority Orders',d.priority_orders,Clock3,'danger'],['Delayed',d.delayed_orders,AlertTriangle,'danger'],['Ready to Pick',d.ready_to_pick,ClipboardList,'blue'],['Ready to Pack',d.ready_to_pack,Box,'blue'],['Ready to Ship',d.ready_to_ship,Truck,'green']].map(([t,v,I,c])=><div className="stat" key={t}><div className={'stat-icon '+c}><I size={19}/></div><div><span>{t}</span><strong>{v}</strong></div></div>)}</div>
 <div className="grid-2"><section className="card"><div className="section-head"><div><h2>Urgent Orders</h2><p>Priority work that needs attention first.</p></div><button className="text-btn" onClick={()=>go('Orders')}>View all</button></div>{d.urgent_orders.length?<table><thead><tr><th>Order</th><th>Customer</th><th>Status</th><th>Deadline</th></tr></thead><tbody>{d.urgent_orders.map(o=><tr key={o.id}><td><b>{o.order_number}</b></td><td>{o.customer_name}</td><td><Status s={o.status}/></td><td className={new Date(o.deadline)<new Date()?'overdue':''}>{fmt(o.deadline)}</td></tr>)}</tbody></table>:<Empty text="No urgent orders"/>}</section>
 <section className="card"><div className="section-head"><div><h2>Attention Required</h2><p>Exceptions that can cause fulfillment delays.</p></div></div>{d.low_stock.map(x=><div className="alert-row" key={x.sku}><AlertTriangle size={18}/><div><b>{x.sku} · {x.name}</b><span>Main: {x.main} · Secondary: {x.secondary}</span></div><em>{x.status}</em></div>)}<div className="alert-row issue"><AlertTriangle size={18}/><div><b>{d.open_issues} open issues</b><span>Resolve exceptions before they become missed orders.</span></div><em>Action needed</em></div></section></div>
 <section className="card flow"><div className="section-head"><div><h2>Fulfillment Flow</h2><p>Current order distribution across the process.</p></div></div><div className="flowline">{['Received','Picking','Packed','Staged','Shipped'].map((s,i)=><React.Fragment key={s}><div className="flow-step"><strong>{d.status_counts[s]||0}</strong><span>{s}</span></div>{i<4&&<span className="arrow">→</span>}</React.Fragment>)}</div></section></>}

function Orders({go,refresh}){const [orders,setOrders]=useState([]),[q,setQ]=useState(''),[status,setStatus]=useState('All'),[priority,setPriority]=useState('All');useEffect(()=>{api.get('/orders',{params:{q,status,priority}}).then(r=>setOrders(r.data))},[q,status,priority,refresh]);return <section className="card"><div className="section-head"><div><h2>Orders</h2><p>Search and manage every fulfillment order.</p></div></div><div className="filters"><div className="search"><Search size={17}/><input placeholder="Search order, customer or SKU" value={q} onChange={e=>setQ(e.target.value)}/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option>All</option>{['Received','Picking','Packed','Staged','Shipped'].map(x=><option key={x}>{x}</option>)}</select><select value={priority} onChange={e=>setPriority(e.target.value)}><option>All</option><option>High</option><option>Normal</option></select></div><table><thead><tr><th>Order</th><th>Customer</th><th>Items</th><th>Priority</th><th>Status</th><th>Courier</th><th>Deadline</th></tr></thead><tbody>{orders.map(o=><tr className="clickable" key={o.id} onClick={()=>go('Order:'+o.id)}><td><b>{o.order_number}</b></td><td>{o.customer_name}</td><td>{o.items.length}</td><td><Priority p={o.priority}/></td><td><Status s={o.status}/></td><td>{o.courier}</td><td className={new Date(o.deadline)<new Date()&&o.status!=='Shipped'?'overdue':''}>{fmt(o.deadline)}</td></tr>)}</tbody></table></section>}

function Inventory({refresh}){const [rows,setRows]=useState([]),[sku,setSku]=useState(''),[qty,setQty]=useState(1),[msg,setMsg]=useState('');const load=()=>api.get('/inventory').then(r=>setRows(r.data));useEffect(load,[refresh]);const transfer=async()=>{try{await api.post('/transfers',{sku,quantity:qty});setMsg('Stock transfer completed.');setSku('');load()}catch(e){setMsg(e.response?.data?.error||'Transfer failed.')}};return <><section className="card"><div className="section-head"><div><h2>Inventory</h2><p>Visibility across the main and secondary warehouses.</p></div></div><table><thead><tr><th>SKU</th><th>Product / Variant</th><th>Main</th><th>Secondary</th><th>Total</th><th>Status</th></tr></thead><tbody>{rows.map(x=><tr key={x.product.sku}><td><b>{x.product.sku}</b></td><td>{x.product.name}<span className="muted">{x.product.variant}</span></td><td>{x.main}<span className="muted">{x.main_location}</span></td><td>{x.secondary}<span className="muted">{x.secondary_location}</span></td><td>{x.total}</td><td><Badge text={x.status} tone={x.status==='Available'?'green':x.status==='Out of Stock'?'red':'amber'}/></td></tr>)}</tbody></table></section><section className="card transfer"><div><h2>Quick Stock Transfer</h2><p>Move stock from the secondary warehouse into the main warehouse.</p></div><div className="transfer-form"><select value={sku} onChange={e=>setSku(e.target.value)}><option value="">Select SKU</option>{rows.filter(x=>x.secondary>0).map(x=><option key={x.product.sku} value={x.product.sku}>{x.product.sku} · {x.product.name}</option>)}</select><input type="number" min="1" value={qty} onChange={e=>setQty(e.target.value)}/><button className="primary" disabled={!sku} onClick={transfer}>Transfer Stock <ArrowRightLeft size={16}/></button></div>{msg&&<p className="success">{msg}</p>}</section></>}

function Queue({status,next,title,refresh}){const [orders,setOrders]=useState([]);const load=()=>api.get('/orders',{params:{status}}).then(r=>setOrders(r.data));useEffect(load,[status,refresh]);const advance=async id=>{await api.patch('/orders/'+id+'/status',{status:next});load()};return <section className="card"><div className="section-head"><div><h2>{title}</h2><p>Keep the next action obvious and easy to confirm.</p></div></div><div className="queue">{orders.length?orders.map(o=><div className="queue-card" key={o.id}><div className="queue-top"><Priority p={o.priority}/><span>{o.courier}</span></div><h3>{o.order_number}</h3><p>{o.customer_name}</p>{o.items.map(x=><div className="item" key={x.sku}><b>{x.product}</b><span>{x.variant} · Qty {x.quantity}</span></div>)}{o.box_id&&<div className="location">Box: {o.box_id}</div>}{o.staging_location&&<div className="location">Location: {o.staging_location}</div>}<div className="queue-bottom"><span className={new Date(o.deadline)<new Date()?'overdue':''}><Clock3 size={15}/> {fmt(o.deadline)}</span><button className="primary" onClick={()=>advance(o.id)}>{next==='Packed'?'Confirm Pick':next==='Staged'?'Mark Staged':'Confirm Shipped'} <CheckCircle2 size={15}/></button></div></div>):<Empty text="No orders in this queue"/>}</div></section>}

function Shipping({refresh}){const [rows,setRows]=useState([]);useEffect(()=>{api.get('/shipments').then(r=>setRows(r.data))},[refresh]);return <section className="card"><div className="section-head"><div><h2>Courier Pickups</h2><p>See whether packed orders are ready before the pickup window.</p></div></div><table><thead><tr><th>Courier</th><th>Pickup</th><th>Orders</th><th>Ready</th><th>Shipped</th><th>Status</th></tr></thead><tbody>{rows.map(x=><tr key={x.courier}><td><b>{x.courier}</b></td><td>{fmt(x.pickup_time)}</td><td>{x.orders}</td><td>{x.ready}</td><td>{x.shipped}</td><td><Badge text={x.status} tone={x.status==='Completed'?'green':'amber'}/></td></tr>)}</tbody></table></section>}

function Issues({refresh}){const [rows,setRows]=useState([]);const load=()=>api.get('/issues').then(r=>setRows(r.data));useEffect(load,[refresh]);const resolve=async id=>{await api.patch('/issues/'+id+'/resolve');load()};return <section className="card"><div className="section-head"><div><h2>Issues</h2><p>Turn informal problems into trackable actions.</p></div></div><table><thead><tr><th>Issue</th><th>Order</th><th>Type</th><th>Description</th><th>Priority</th><th>Status</th><th></th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><b>ISS-{String(x.id).padStart(3,'0')}</b></td><td>{x.order}</td><td>{x.issue_type}</td><td>{x.description}</td><td><Priority p={x.priority}/></td><td><Badge text={x.status} tone={x.status==='Resolved'?'green':'red'}/></td><td>{x.status==='Open'&&<button className="small-btn" onClick={()=>resolve(x.id)}>Resolve</button>}</td></tr>)}</tbody></table></section>}

function OrderDetail({id,onBack}){const [data,setData]=useState(null);const load=()=>api.get('/orders/'+id).then(r=>setData(r.data));useEffect(load,[id]);if(!data)return <Loading/>;const o=data.order;const next={Received:'Picking',Picking:'Packed',Packed:'Staged',Staged:'Shipped'}[o.status];return <section><button className="back" onClick={onBack}>← Back to Orders</button><div className="detail-grid"><div className="card"><div className="detail-head"><div><div className="eyebrow">ORDER</div><h2>{o.order_number}</h2><p>{o.customer_name} · {o.courier}</p></div><div><Priority p={o.priority}/><Status s={o.status}/></div></div><div className="timeline">{['Received','Picking','Packed','Staged','Shipped'].map((s,i)=>{const active=['Received','Picking','Packed','Staged','Shipped'].indexOf(o.status)>=i;return <div className={active?'time active':'time'} key={s}><span>{active?'✓':i+1}</span><b>{s}</b></div>})}</div><h3>Items</h3>{o.items.map(x=><div className="detail-item" key={x.sku}><div><b>{x.product}</b><span>{x.sku} · {x.variant}</span></div><strong>Qty {x.quantity}</strong></div>)}{next&&<button className="primary wide" onClick={async()=>{await api.patch('/orders/'+id+'/status',{status:next});load()}}>{next==='Picking'?'Start Picking':next==='Packed'?'Confirm Pick & Pack':next==='Staged'?'Move to Staging':'Confirm Courier Handover'} <CheckCircle2 size={16}/></button>}</div><div className="card"><h2>Inventory Check</h2>{data.inventory.map(x=><div key={x.sku} className="inventory-check"><b>{x.sku}</b><span>Required: {x.required}</span>{x.warehouses.map(w=><div className="wh" key={w.warehouse}><span>{w.warehouse}</span><strong>{w.quantity}</strong><small>{w.location}</small></div>)}</div>)}<h2 className="issue-title">Order Issues</h2>{data.issues.length?data.issues.map(i=><div className="mini-issue" key={i.id}><b>{i.type}</b><span>{i.description}</span></div>):<p className="muted">No issues reported.</p>}</div></div></section>}

function Status({s}){return <Badge text={s} tone={s==='Shipped'?'green':s==='Packed'||s==='Staged'?'blue':s==='Picking'?'amber':'neutral'}/>};function Priority({p}){return <Badge text={p==='High'?'● High':'Normal'} tone={p==='High'?'red':'neutral'}/>};function Badge({text,tone}){return <span className={'badge '+tone}>{text}</span>};function Empty({text}){return <div className="empty">{text}</div>};function Loading(){return <div className="loading">Loading…</div>}

function Root(){const [selected,setSelected]=useState(null);const [page,setPage]=useState('Dashboard');const [refresh,setRefresh]=useState(0);if(selected)return <div className="app"><aside><Side page={page} setPage={p=>{setPage(p);setSelected(null)}}/></aside><main><header><div><div className="eyebrow">XYZ / OPERATIONS</div><h1>Order Details</h1></div><button className="icon-btn" onClick={()=>setRefresh(x=>x+1)}><RefreshCw size={18}/></button></header><OrderDetail id={selected} onBack={()=>setSelected(null)}/></main></div>;return <AppWithOpen setSelected={setSelected}/>}
function Side({page,setPage}){const nav=[['Dashboard',LayoutDashboard],['Orders',ShoppingCart],['Inventory',PackageSearch],['Picking',ClipboardList],['Packing',Box],['Staging',MapPin],['Shipping',Truck],['Issues',AlertTriangle]];return <><div className="brand"><div className="brand-mark">FH</div><div><b>Fulfillment Hub</b><span>XYZ Operations</span></div></div><nav>{nav.map(([n,I])=><button key={n} className={page===n?'active':''} onClick={()=>setPage(n)}><I size={18}/>{n}</button>)}</nav><div className="sidebar-note"><b>Simple by design</b><span>Built for office & warehouse teams.</span></div></>}
function AppWithOpen({setSelected}){const [page,setPage]=useState('Dashboard');const [refresh,setRefresh]=useState(0);const content={Dashboard:<Dashboard go={setPage}/>,Orders:<Orders go={p=>p.startsWith('Order:')?setSelected(Number(p.split(':')[1])):setPage(p)} refresh={refresh}/>,Inventory:<Inventory refresh={refresh}/>,Picking:<Queue status="Picking" next="Packed" title="Picking Queue" refresh={refresh}/>,Packing:<Queue status="Packed" next="Staged" title="Packing Queue" refresh={refresh}/>,Staging:<Queue status="Staged" next="Shipped" title="Staging & Shipping Queue" refresh={refresh}/>,Shipping:<Shipping refresh={refresh}/>,Issues:<Issues refresh={refresh}/>};return <div className="app"><aside><Side page={page} setPage={setPage}/></aside><main><header><div><div className="eyebrow">XYZ / OPERATIONS</div><h1>{page}</h1></div><button className="icon-btn" onClick={()=>setRefresh(x=>x+1)}><RefreshCw size={18}/></button></header>{content[page]}</main></div>}

createRoot(document.getElementById('root')).render(<Root/>);
